### ISSUE TITLE
Add support for Pydantic

### ISSUE THREAD

**Issue by limmyforget** [apiflask/apiflask#128]
Can you join the support of pydantic, so that users can choose more than one, so that people who like different styles can choose freely according to their hobbies, thank you

**Comment by greyli** [comment]
Add support for [marshmallow-dataclass](https://github.com/lovasoa/marshmallow_dataclass) may be an easier option.

**Comment by greyli** [comment]
As the project grows, it involves more and more features from marshmallow projects. Supporting Pydantic requires too much refactoring, I don't think it will happen in 2.0.

Just use other Flask extensions/tools with Pydantic support (e.g. [Spectree](https://github.com/0b01001001/spectree)). Closing now.
