### ISSUE TITLE
Add support for marshmallow-dataclass

### ISSUE THREAD

**Issue by greyli** [apiflask/apiflask#242]
https://github.com/lovasoa/marshmallow_dataclass

**Comment by mmdbalkhi** [comment]
I can work on this @greyli

one question, will this be **optional**? And its installation can be like the following command?

```sh
    pip install "apiflask [marshmallow-db]"
```

**Comment by greyli** [comment]
Great!

> And its installation can be like the following command?

Yes, maybe use `mashmallow-dataclass` or just `dataclass`, `db` makes people think about "database" :P

**Comment by mmdbalkhi** [comment]
@greyli I was looking at the code yesterday to see where I should write it. If I'm not mistaken I have to edit the `app.py` and `scaffold.py` files, right? (based on schemas) but this changes the structure of the program. Can you suggest I design a new structure so that the previous structure does not change?

**Comment by greyli** [comment]
What do you mean by "changes the structure of the program"?

IMO, this feature will involve the following steps (it seems no need to edit `app.py`):

- Update `scaffold.Scaffold.input` to detect and convert data classes to marshmallow schema.
- Update `scaffold.Scaffold.output` to detect and convert data classes to marshmallow schema.
- Add a new extra install item to setup.py
- Add tests
- Update docs
- Update changelog

**Comment by mmdbalkhi** [comment]
Hello. I wrote the code, but part of the code requires base_schema to be `Schema` (because the `dump` method is not available for `dataclass`) What do you think can be done about this? ( sorry I asked many questions)

e.g: similar to the base response example code

```py
...

class BaseResponseSchemas(Schema):
    message = String()
    status_code = Integer()
    data = Field()  # the data key

...
@dataclass
class PetInSchema:
    name = String(required=True, validate=Length(0, 10))
    category = String(required=True, validate=OneOf(["dog", "cat"]))


@dataclass
class PetOutSchema:
    id = Integer()
    name = String()
    category = String()
...
```

**Comment by greyli** [comment]
Can we convert the data class to the marshmallow schema class at the beginning of the `output` method?

It's OK, feel free to ask any related questions here.

**Comment by mmdbalkhi** [comment]
> Can we convert the data class to the marshmallow schema class at the beginning of the `output` method?

yes can we do it with this

Currently, the only problem is with the input. Solve it and I push the tests and docs to close this issue

**Comment by mmdbalkhi** [comment]
@greyli The program currently has an input problem and I do not know what. For example, when we run the tests, the error test returns 400:

```py
FAILED examples/test_examples.py::test_create_pet[dataclass] - assert 400 == 201
FAILED examples/test_examples.py::test_update_pet[dataclass] - assert 400 == 200
```

**Comment by mmdbalkhi** [comment]
Great! The problem was solved. I had forgotten a small thing in the documentation
