### ISSUE TITLE
Add file validators for File field

### ISSUE THREAD

**Issue by greyli** [apiflask/apiflask#253]
Add `FileType` and `FileSize` validators.

**Comment by uncle-lv** [comment]
I’m working on this issue, but having a problem.
I tried to send a test request with specified content_length:
```python
rv = client.post(
    '/',
    data={
        'image': (io.BytesIO(b'test'), 'test.jpg'),
    },
    content_type='multipart/form-data',
    content_length=2097153
)
```
But the content_length I got was always zero.
I'm not familiar with werkzeug. How can I do it right?

**Comment by uncle-lv** [comment]
By the way, this is my work.
```python
class ValidateFiles(Schema):
    image = File(accept=['image/jpeg'], maxsize=2)
```
**accept**: A list of strings, it works the same way as [accept](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept).
**maxsize**: An integer, limits file size to less than `maxsize` **MB**.

Is it OK?

**Comment by uncle-lv** [comment]
> I’m working on this issue, but having a problem. I tried to send a test request with specified content_length:
> 
> ```python
> rv = client.post(
>     '/',
>     data={
>         'image': (io.BytesIO(b'test'), 'test.jpg'),
>     },
>     content_type='multipart/form-data',
>     content_length=2097153
> )
> ```
> 
> But the content_length I got was always zero. I'm not familiar with werkzeug. How can I do it right?

It seems not a good way to get the file size according to `content_length`. So please ignore it.

**Comment by greyli** [comment]
> By the way, this is my work.
> 
> ```python
> class ValidateFiles(Schema):
>     image = File(accept=['.jpg'], maxsize=2)
> ```
> 
> **accept**: A list of strings, it works the same way as [accept](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept). **maxsize**: An integer, limits file size to less than `maxsize` **MB**.
> 
> Is it OK?

Please use the consistent API to implement the validator, for example:

```python
from apiflask.validators import FileType, FileSize

class FilesSchema(Schema):
    image = File(validator=[FileType(['.jpg']), FileSize(max=2))
```

You can refer to the implementation of [other validators in marshmallow](https://marshmallow.readthedocs.io/en/stable/marshmallow.validate.html) and the [`FileSize` the `FileAllowed` validator](https://github.com/wtforms/flask-wtf/blob/main/src/flask_wtf/file.py#L42) in Flask-WTF.

**Comment by uncle-lv** [comment]
> > By the way, this is my work.
> > ```python
> > class ValidateFiles(Schema):
> >     image = File(accept=['.jpg'], maxsize=2)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **accept**: A list of strings, it works the same way as [accept](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept). **maxsize**: An integer, limits file size to less than `maxsize` **MB**.
> > Is it OK?
> 
> Please use the consistent API to implement the validator, for example:
> 
> ```python
> from apiflask.validators import FileType, FileSize
> 
> class FilesSchema(Schema):
>     image = File(validator=[FileType(['.jpg']), FileSize(max=2))
> ```
> 
> You can refer to the implementation of [other validators in marshmallow](https://marshmallow.readthedocs.io/en/stable/marshmallow.validate.html) and the [`FileSize` the `FileAllowed` validator](https://github.com/wtforms/flask-wtf/blob/main/src/flask_wtf/file.py#L42) in Flask-WTF.

Got it!
