### ISSUE TITLE
Add `app.paginate()` decorator

### ISSUE THREAD

**Issue by greyli** [apiflask/apiflask#256]
Add more support to pagination.

**Comment by 9gl** [comment]
Hey @greyli  ,
 I'm interested in contributing to this issue, so before I start working on it, would you mind sparing your time explaining what the issue is about and pointing me to some resources to get started.

**Comment by greyli** [comment]
> Hey @greyli , I'm interested in contributing to this issue, so before I start working on it, would you mind sparing your time explaining what the issue is about and pointing me to some resources to get started.

Hi 9gl, thanks for the interest. I'm not sure if we could make this feature happen. I was thinking of a decorator to paginate the list response (something like the `paginate` decorator in flask-smorest), but we can't access the `app.config` object in the decorator (the `input` can be `app.input` or `bp.input`), so we can't provide global configurations for things like page, per_page, max_page (it make no sense to let user pass these values per view function).
