### ISSUE TITLE
Support skipping request validation

### ISSUE THREAD

**Issue by greyli** [apiflask/apiflask#257]
Add a boolean arg `skip_validation` to `app.input()`

**Comment by greyli** [comment]
I hope this could become a global configuration, but we cannot access the `app.config` object in the `input` decorator since it could be called by a blueprint object (`bp.input()`).

**Comment by 9gl** [comment]
Hey @greyli ,
I'm interested in contributing to this issue, so before I start working it, would you mind sparing your time explaining what the issue is about and pointing me to some resources to get started.

**Comment by henryx** [comment]
Hi,

Any news about this?

**Comment by greyli** [comment]
I didn't find a clean way to achieve this in APIFlask. I think the support to skip validation should be added upstream (webargs).

Closing for now. Please create an issue to webargs if you think it is a useful feature. webargs could support passing a `skip_validation` arg in `use_args()` function, that's what APIFlask's `app.input()` called underly.
