### ISSUE TITLE
Consider removing the validation for input location

### ISSUE THREAD

**Issue by greyli** [apiflask/apiflask#259]
In the current implementation, if the user uses an unsupported input location in `app.input(location=...)`, APIFlask will raise a ValueError.

Pros:

- Allow users to create a custom location loader

Cons:

- No error is raised if the user uses a bad location (typo)

**Comment by mmdbalkhi** [comment]
Hello, I want to work on this, can you give me more information?

**Comment by greyli** [comment]
Just remove [these lines](https://github.com/apiflask/apiflask/blob/main/src/apiflask/scaffold.py#L302-L307) and the related variable. Also, update tests and changelog.
