### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by greyli** [apiflask/apiflask#271]
- Add more code examples to the Data Schema chapter (mention Meta schema, `unknown`, `many`, `partial`)
- Add token, basic, and apiKey section to the Security chapter
- Add more info to the Comparison and Motivations chapter

**Comment by FarmerChillax** [comment]
Flask 依赖更新后，也许这部分的文档也需要稍微的调整一下：https://apiflask.com/usage/#create-a-route-with-route-decorators

**Comment by boring-plans** [comment]
Already fascinated by this awesome framework! I found two super tiny mistakes in the [usage section](https://apiflask.com/usage/), and happen to see this issue, so list them out by the way 👻:

- an empty
![image](https://user-images.githubusercontent.com/38272264/202997352-3b486a00-25dc-4c86-9763-3d78bad74f2b.png)

- which is  used / used 
![image](https://user-images.githubusercontent.com/38272264/202998443-b347644f-be15-4139-b294-db5b3f587a1b.png)

**Comment by greyli** [comment]
@boring-plans Thanks! Feel free to make a PR to improve it.

**Comment by greyli** [comment]
Moved to #268
