### ISSUE TITLE
No info on setting default input?

### ISSUE THREAD

**Issue by Ozeitis** [apiflask/apiflask#325]
Hello, it seems there is no info, at least that I could find, that explains how to set default values for the OpenAPI docs route.

**Comment by greyli** [comment]
What does "setting default input" mean? Can you provide an example?

**Comment by greyli** [comment]
I think you may refer to the `docs_ui` argument in the `APIFlask` class:

```
app = APIFlask(__name__, docs_ui='redoc')
```

https://apiflask.com/api/app/#apiflask.app.APIFlask.__init__
