### ISSUE TITLE
Cannot use custom decorator more than once

### ISSUE THREAD

**Issue by duchuyvp** [apiflask/apiflask#332]
Let me give a brief description

Here is my decorator:
```python
def test_decorator():
    def decorator(f):
        def wrapper(*args, **kwargs):
            return f(*args, **kwargs)

        return wrapper

    return decorator
```

This code seem work, but name was generated as "Wrapper" on `/docs`
```python
@api.get("/endpoint1")
@test_decorator()
def get_endpoint1():
    return "Hello World!"
```

But when I use that decorator tiwce, I receive `AssertionError: View function mapping is overwriting an existing endpoint function: api.wrapper`
```python

@api.get("/endpoint1")
@test_decorator()
def get_endpoint1():
    return "Hello World!"


@api.get("/endpoint2")
@test_decorator()
def get_endpoint2():
    return "Hello World!"
```

I don't know that was a bug or my decorator function has an error, please help me! 

Environment:

- Python version: 3.7.9
- Flask version: 2.1.2
- APIFlask version: 1.1.0

**Comment by greyli** [comment]
The decorator will change the raw function (name, docstring, etc.), try to use `functools.wraps` to keep the decorated function unchanged.


```python
from functools import wraps


def test_decorator():

    def decorator(f):
        @wraps(f)
        def wrapper(*args, **kwargs):
            return f(*args, **kwargs)

        return wrapper

    return decorator
```
