### ISSUE TITLE
apidoc broken when used in a non-root relative path

### ISSUE THREAD

**Issue by stampycode** [apiflask/apiflask#334]
Say I have a container hosting my apidoc endpoint at `/api/myapp/apidoc`
I don't know when I build my application what '/api/myapp' will be, so I can't hardcode it.
With Flask, paths are relative, but with APIFlask, `spec_path` and `docs_path` must be absolute URLs when you configure the server.

When I say `docs_path='/apidoc'` this works, I can access apidoc at '/api/myapp/apidoc' without issue.

When I say `spec_path='/openapi'` this is broken, because the `/apidoc` now tries to load the spec from `/openapi` instead of `/api/myapp/openapi`.

When I hardcode `spec_path='/api/myapp/openapi'` this half-works, because the UI now finds the openapi resource but now the actual hosted location of the specification is `/api/myapp/api/myapp/openapi`. The only way around this is to add a dodgy redirect to tell the UI the new location of the spec document.

I've tried using various 'relative path' switches and a variety of different configurations but I haven't made it work sensibly yet. Even when I do get it working to the point where the UI loads, the in-built API forms are all broken because they ignore the base relative dir....

In the documentation ( https://apiflask.com/openapi/#keep-the-local-spec-in-sync ) it says "If the path you passed is relative, do not put a leading slash in it" but its impossible to use the spec_path or docs_path parameters without prefixing a slash, Flask just throws a "must be an absolute path" exception.

This is the semi-working end result I've come up with, if anyone can suggest where I can improve this I'd be very grateful.

```
from apiflask import APIFlask
from flask import Flask, request, jsonify, redirect

app = APIFlask(
    __name__, static_folder=None, title="My Container", spec_path='/api/myapp/openapi', docs_path='/apidoc'
)

@app.route('/openapi', methods=['GET'])
def openapi():
    response = jsonify()
    response.status_code = 302
    response.headers['Location'] = '/api/myapp/api/myapp/openapi'
    response.autocorrect_location_header = False
    return response

```

Environment:

- Python version: 3.7.11
- Flask version: 1.1.2
- APIFlask version: 1.1.0

**Comment by greyli** [comment]
Hi, thanks for the detailed explanation. Can you provide a minimal and complete code example that can reproduce your initial issue? Especially for:

> When I say spec_path='/openapi' this is broken, because the /apidoc now tries to load the spec from /openapi instead of /api/myapp/openapi.

BTW, the doc at https://apiflask.com/openapi/#keep-the-local-spec-in-sync is about the local spec *file path*.

**Comment by greyli** [comment]
Please verify APIFlask 1.2.1 fixes this issue, thanks.

```
pip install -U apiflask
```
