### ISSUE TITLE
change the default validation error status_code

### ISSUE THREAD

**Issue by hjlarry** [apiflask/apiflask#345]
We should change the default `VALIDATION_ERROR_STATUS_CODE` to 422, and now it's 400.

There are 3 reasons:

1. as the [RFC4918](https://www.rfc-editor.org/rfc/rfc4918#section-11.2) described:
```
   The 422 (Unprocessable Entity) status code means the server
   understands the content type of the request entity (hence a
   415(Unsupported Media Type) status code is inappropriate), and the
   syntax of the request entity is correct (thus a 400 (Bad Request)
   status code is inappropriate) but was unable to process the contained
   instructions.  For example, this error condition may occur if an XML
   request body contains well-formed (i.e., syntactically correct), but
   semantically erroneous, XML instructions.
```

2. the other well-known product also use 422 to describe the validation error,  like [github api](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#client-errors), [fastapi](https://github.com/tiangolo/fastapi/blob/master/fastapi/exception_handlers.py#L23)

3. In apiflask, if I raise a marshallow's validation error,  or  post a json without a `}`,  they both raise the same 400 bad request, but they are not the same error.

I try to fix that, but there are lots of unittests to modify. If you guys agree with that,  I can work a pr with that.

**Comment by greyli** [comment]
I'm okay with this change. It seems to be a potential breaking change, maybe we should merge it for version 1.2 or 2.0 after 1.1.3 is released.
