### ISSUE TITLE
HTTPError Not Updating

### ISSUE THREAD

**Issue by Fangjun-Zhou** [apiflask/apiflask#351]
# Description

When adding a new HTTPError or removing an existing one, the document will not change.
It first came to my project that no HTTPError is displaying, then I tried the samples and found that for some reason, the document will store all the HTTPError for the first time and never change.

# How to Replicate

- Clone the project and open the [example](https://github.com/apiflask/apiflask/tree/main/examples)
- Run an example. I chose [base_response](https://github.com/apiflask/apiflask/tree/main/examples/base_response)

Notice code block:

```python
@app.delete('/pets/<int:pet_id>')
@app.output({}, status_code=204)
def delete_pet(pet_id):
    if pet_id > len(pets) - 1:
        abort(404)
    pets[pet_id]['deleted'] = True
    pets[pet_id]['name'] = 'Ghost'
    return ''
```

The following document is generated:

![image](https://user-images.githubusercontent.com/79500078/187554933-ce5b83f6-cb98-4b23-949a-982c9ab309f4.png)

Remove the abort part by:

```python
@app.delete('/pets/<int:pet_id>')
@app.output({}, status_code=204)
def delete_pet(pet_id):
    # if pet_id > len(pets) - 1:
    #     abort(404)
    pets[pet_id]['deleted'] = True
    pets[pet_id]['name'] = 'Ghost'
    return ''
```

Restart the flask service, the same document is generated:

![image](https://user-images.githubusercontent.com/79500078/187555091-68fbb855-89ac-4e47-8af1-170f3e73f158.png)

I tried to clone the project and comment out one abort call. And the document does not show the HTTPError as expected, but later when I uncomment the code the document is still the same.

I'm not sure if anyone else had this problem before or if it is just me. I tried everything, clearing the Chome cache, and restarting the flask entirely, but nothing is working.

Environment:

- Python version: 3.10.6
- Flask version: 2.2.2
- APIFlask version: 1.1.2

**Comment by greyli** [comment]
Hi! The `abort` won't change the HTTP errors' OpenAPI spec of an endpoint. The OpenAPI spec will only be changed with decorators (`input`, `output`, `doc`, `auth_required`).

You can set the `responses` parameter of the `app.doc()` decorator to manually set the errors for an endpoint:

```python
@app.delete('/pets/<int:pet_id>')
@app.output({}, status_code=204)
@app.doc(responses={404: 'something missing', 500: 'something was wrong'})
def delete_pet(pet_id):
    ...
```

Besides, beware that APIFlask will add some errors automatically. For example, if an endpoint's URL rule contains variables, it will add a 404 error. These behaviors can be controlled with some configurations: https://apiflask.com/configuration/#auto_404_response
