### ISSUE TITLE
How to properly document a file response?

### ISSUE THREAD

**Issue by edugonza** [apiflask/apiflask#357]
Hi.

I wonder if there is a proper way to document the output of an endpoint that returns a file as a response. I haven't found anything in the documentation. If a method exists, it would be good to include an example.

Thank you
KR
Eduardo

**Comment by greyli** [comment]
Hi Eduardo. Currently, you can only update the spec manually with the [spec_processor](https://apiflask.com/openapi/#register-a-spec-processor). I will try to find a way to customize the media type of response, now the media type is forced to JSON.

By the way, what's your view function look like? Can you provide a minimal example?

**Comment by pamelafox** [comment]
I have a similar use case:

```
from io import BytesIO

from apiflask import APIFlask, Schema
from apiflask.fields import DelimitedList, Number, String
from apiflask.validators import Length, Range
from flask import send_file, Response
from matplotlib.axes import Axes
from matplotlib.figure import Figure

app = APIFlask(__name__, docs_path=None)

def send_figure_as_png(fig:Figure) -> Response:
    # Save it to a temporary buffer.
    buf = BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    return send_file(buf, download_name="chart.png", mimetype="image/png")

class BarChartParams(Schema):
    title = String(required=False, validate=Length(0, 30))
    xlabel = String(required=False, validate=Length(0, 30))
    ylabel = String(required=False, validate=Length(0, 30))
    xvalues = DelimitedList(String, required=True)
    yvalues = DelimitedList(Number, required=True)


@app.get("/bar_chart")
@app.input(BarChartParams, location="query")
def bar_chart(data:dict):
    fig = Figure()
    axes:Axes = fig.subplots(squeeze=False)[0][0]
    axes.bar(data["xvalues"], data["yvalues"])
    axes.set_xlabel(data.get("xlabel", ""))
    axes.set_ylabel(data.get("ylabel", ""))
    axes.set_title(data.get("title", ""))
    axes.set_ylim(bottom=0)
    return send_figure_as_png(fig)
```

**Comment by pamelafox** [comment]
Here's the workaround as suggested:

```
@app.spec_processor
def update_spec(spec):
    spec['paths']['/bar_chart']['get']['responses']['200']['content'] = {
        "image/png": {
            "schema": {
                "type": "string",
            }
        }
    }
    return spec
```

It does work, but it'd be great if there was built-in support. Thanks!

**Comment by greyli** [comment]
Hi guys, in APIFlask 1.3.0, there will be a `content_type` parameter that you can use to customize the content type:

```python
@app.post('/image')
@app.output(ImageOutSchema, content_type='image/png')
def get_image():
    pass
```

**Comment by pamelafox** [comment]
Thanks! I'm using that now. Can you confirm that this is what's expected for the definition of ImageOut Schema? (i.e. no fields defined)

```
class ImageOutSchema(Schema):
    pass
```

You can see my full usage here:
https://github.com/pamelafox/flask-charts-api-container-app/blob/main/src/api/__init__.py

**Comment by greyli** [comment]
Nope. That's just an example. You should use the `File` field:

```py
from apiflask.fields import File


class ImageOutSchema(Schema):
    image = File()
```

This will generate the following spec:

```
"components": {
    "ImageOut": {
        "type": "object",
        "properties": {
          "image": {
            "type": "string",
            "format": "binary"
          }
        }
      },
    ...
}
```

**Comment by greyli** [comment]
I see. Based on OpenAPI 3.0 docs, the schema here should be:

```
image/png:
    schema:
        type: string
        format: binary
```

You can use the empty schema for now. I will add a built-in schema for file response later.

**Comment by haifishtime** [comment]
> I see. Based on [OpenAPI 3.0 docs](https://swagger.io/docs/specification/describing-responses/), the schema here should be:
> 
> ```
> image/png:
>     schema:
>         type: string
>         format: binary
> ```
> 
> If we use the `File` field as described in my last comment, then it will generate a schema with a key, but here the whole response is a file.
> 
> I will add a built-in schema for file response ~this~next weekend.

Hey! As far as I can see there is not yet a built-in schema for this. Any updates on it?
I had to use the workaround with spec_processer as suggested above to make it work.

**Comment by greyli** [comment]
> I will add a built-in schema for file response ~this~next weekend.

It didn't finish "next weekend", but I finally got it done. The `FileSchema `is added in https://github.com/apiflask/apiflask/pull/448

**Comment by pamelafox** [comment]
Woot! Looking forward to the next release.
