### ISSUE TITLE
there is an issue when use pyinstaller

### ISSUE THREAD

**Issue by zhaoweipp** [apiflask/apiflask#409]
Environment:

- Python version:
- Flask version:
- APIFlask version:

**Comment by zhaoweipp** [comment]
when i use pyinstaller,the apiflask.settings not found.
Debugged import:

- 'apiflask' found in 'C:\\Users\\xx\\AppData\\Local\\Temp\\_MEI179682\\apiflask\\__init__.pyc'.
- 'apiflask.settings' not found.

Original exception:

ImportError: module 'apiflask' has no attribute 'settings'
[14516] Failed to execute script 'manager' due to unhandled exception!

sorry,i am not good at python,can you help me，thx！

**Comment by zhaoweipp** [comment]
好像可以使用中文呢，我还是中文描述一下吧，不好意思。
我在本地使用python manager.py runserver的时候是可以正常运行的，
但是使用pyinstaller打包成exe之后,就会报错,好像是缺少apiflask的setting文件,请问一下这个应该怎么打包呢？python学的不好,麻烦帮帮忙！谢谢！

**Comment by greyli** [comment]
用中文的话，麻烦移步到下面的论坛来讨论吧，谢谢。

https://discuss.helloflask.com/t/topic/1014

**Comment by greyli** [comment]
Duplicated with #368
