### ISSUE TITLE
Pass arguments in kwargs to view functions (same behavior as flask)

### ISSUE THREAD

**Issue by chahu** [apiflask/apiflask#427]
I recently bumped into an issue trying to convert an existing flask project to use apiflask. One of my view functions has a decorator which relies on arguments being passed as keyword arguments (kwargs) to work correctly. It appears apiflask does not pass arguments the same way that flask does when calling view functions. This seems to be by design for some reason, but it can break existing code.

At any rate, there are cases (as above) where the view function or its decorators needs the arguments to be in kwargs.

I found this piece of code in apiflask which will send kwargs (as flask does) if an attribute is set:
```javascript
        if rule.endpoint == 'static' or hasattr(view_function, '_only_kwargs'):
            # app static route only accepts keyword arguments, see flask#3762
            # view classes created by Flask only accept keyword arguments
            return view_function(**req.view_args)  # type: ignore
        else:
            return view_function(*req.view_args.values())  # type: ignore
```

I'm currently using a decorator to help me mark my view function as needing kwargs:
```javascript
def require_kwargs(f):
    """
    Tag a view function as needing kwargs. This is for apiflask which only passes positional
    arguments unless this attribute exists on the view function. 
    """
    f._only_kwargs = True
    return f
```

Usage:
```javascript
@bp.route("/some/path/<my_variable>/", methods=("GET",))
@require_kwargs
@another_decorator_that_needs_kwargs
def my_view_function(my_variable):
    pass
```

A quick search shows I'm not the only one hitting this issue https://github.com/apiflask/apiflask/issues/422 .
Please consider allowing flask-behavior when passing args in kwargs, either globally or on a route-by-route basis, otherwise adopting apiflask in existing projects will be difficult. I suggest making this a global setting to adhere to existing flask behavior.

**Comment by greyli** [comment]
Hi, thanks for the idea. In APIFlask 2.0, I'm thinking of turning all the arguments into keyword arguments. The input data will be passed with the location value as the keyword (`json`, `query`, etc.). For example:

```python
@app.post('/pets/<pet_id>')
@app.input(PetQueryIn, location='json')
@app.input(PetBodyIn, location='query')
@app.output(PetOut, status_code=201)
def create_pet(pet_id, json, query):
    id = json['id']
    query_number = query['number']
```

I already working on this. Since this is a breaking change, I will release this with APIFlask 2.0.

What do you think about this?

**Comment by chahu** [comment]
> 

Thanks for the quick reply. That would be a great solution. My main goal is to have it compatible with existing code that uses flask, so if you pass args in keyword arguments similar to flask this would solve the issue.

**Comment by chahu** [comment]
One slight issue with your example code is if a view function needs to parse or serialize json itself, forcing the argument name to be "json" might be problematic if the function needs to make use of the core json module itself. One solution is to use an alias ( `import json as another_name` ), but you may want to avoid forcing this workaround for such a commonly used module name to avoid confusion,

```python
import json

@app.post('/pets/<pet_id>')
@app.input(PetQueryIn, location='json')
@app.input(PetBodyIn, location='query')
@app.output(PetOut, status_code=201)
def create_pet(pet_id, json, query):
    id = json['id']
    parsed = json.loads('{"example": 5}') # error
```

**Comment by greyli** [comment]
Good point. I'm thinking of setting the default arg name to the `location` value, then adding an `arg_name` to support changing it:

```python
import json

@app.post('/pets/<pet_id>')
@app.input(PetBodyIn, location='json', arg_name='data')  # <--
@app.input(PetQueryIn, location='query')
@app.output(PetOut, status_code=201)
def create_pet(pet_id, data, query):
    id = data['id']
    parsed = json.loads('{"example": 5}')
```

Or how about we set the default arg name to `data` instead of `json`? That could solve the conflict with the `json` module, but there will be a mismatch between the location value (`json`) and the arg name (`data`). Personally, I prefer to use `json` for consistency, then add `arg_name` for customization needs.

What do you think? @chahu @luong-komorebi

**Comment by greyli** [comment]
> Personally, I prefer to use data as the default, then add arg_name for any customization needs.

webargs will use `<location>_args` as the default arg name because their decorator is named `use_args` (https://github.com/marshmallow-code/webargs/pull/833). So I think `<location>_data` as the default name rule may be the best choice for us.

> Another thing I would love to have is a small notice or documentation for APIFlask version < 2.0 in the migrating section [apiflask.com/migrating](https://apiflask.com/migrating/) to note the current behaviour for users migrating from Flask.

Good point, I will add a corresponding section to the migrating docs later.

**Comment by wlach** [comment]
Hey, I ran into a similar problem with an existing codebase, but with a parameter that is specified in the URL string. Will your solution cover that? Example:

```py
@app.post('/pets/<int:pet_id>')
@my_decorator_which_looks_for_a_pet_id_kwarg
def create_pet(pet_id: int):
    ...
```

Will `pet_id` also appear in kwargs somehow with your intended changes outlined above?

**Comment by wlach** [comment]
> However, the thing that changes here is when you manipulate the arguments (or keyword arguments) inside @my_decorator_which_looks_for_a_pet_id_kwarg, it will be successful and the behaviour would be the same as flask

Thanks @luong-komorebi for the quick response, but I'm not sure if I completely understand. Let me flesh this out a bit more: in my application I have a decorator that looks like this (changed to fit the above example):

```py
def my_decorator_which_looks_for_a_pet_id_kwarg(function):
    @wraps(function)
    def decorated_function(*args, **kwargs):
        pet_id = kwargs['pet_id']
        # <insert business logic which does something with pet id>
        ...
```

This doesn't currently work with APIFlask (`pet_id` would appear, but only as the first element of `args`). Are you saying that with APIFlask 2.0 this will now work? Or will it not?

**Comment by greyli** [comment]
Hi @ddominguezb! From APIFlask 2.0, the request input data will always be passed as keyword arguments (default to `{location name}_data`). See the docs for more details:

https://apiflask.com/migration_guide/#use-keyword-argument-for-the-input-data

You just need to change the `params` to `files_data`.

**Comment by ddominguezb** [comment]
@greyli, it worked like a charm! you saved my day

Thank you so much.
