### ISSUE TITLE
Disable openapi for specific route

### ISSUE THREAD

**Issue by duchuyvp** [apiflask/apiflask#429]
Hi, I'm working on apiflask to create web for my company. When I release api documentation for client, they want to hide some apis in the document, which I found that the  solution is disable openapi for those routes. For APIBlueprint, it simply can do with `enable_openapi` parameter, but how to do that for specific route? I did try with `@blp.route('/endpoint', methods = ['GET'],  enable_openapi=False)` but didn't work. Please help me.

**Comment by greyli** [comment]
Try to set the `hide` boolean to `True` with `app.doc`.

https://apiflask.com/openapi/#disable-for-specific-view-functions
