### ISSUE TITLE
how to add description in input parameters

### ISSUE THREAD

**Issue by fzellini** [apiflask/apiflask#441]
Hi,is it possible in  a clean way to add a description in the "parameter" "description" of the resulting openapi.json ?
eg.g
....
name: "uuid",
in: "query",
description: "my great  detailed uuid parameter description"
...
Currently, i not see "description" for parameters in openapi.json

**Comment by greyli** [comment]
You can add description for any schema field with the `metadata={'description': 'Blah...'}` attribute:

```python
class PetInQuery(Schema):
    name = String(metadata={'description': 'The name of the pet.'})
```
