### ISSUE TITLE
Drop Flask 1.x support

### ISSUE THREAD

**Issue by greyli** [apiflask/apiflask#442]

**Comment by reteps** [comment]
Is there an explicit reason this was done @greyli ?

**Comment by reteps** [comment]
My team works on a large codebase that is slowly porting to Flask 2, but were thinking of using this library.

**Comment by greyli** [comment]
I want to match the Flask version (APIFlask 2 - Flask 2). You could pin APIFlask <2 if you are using Flask 1.x.
