### ISSUE TITLE
Warn or throw when returning a value not in a response schema

### ISSUE THREAD

**Issue by wlach** [apiflask/apiflask#470]
Currently it appears that APIFlask silently filters out values from the response that are not in the schema.

Trivial example:

```py
class PetOut(Schema):
    id = Integer()
    name = String()

@app.get('/pet')
@app.output(PetOut)
def get_pet():
    return {
        'id': 1234,
        'name': 'Fido',
        'category': 'Dog'  # will not appear in response
    }
```

Would it be possible to add an opt-in assertion to fail for this case, or at least create a warning? This behaviour can result in subtle, hard to diagnose bugs.

**Comment by greyli** [comment]
This behaviour is intentional, please see https://github.com/marshmallow-code/marshmallow/issues/1198 for the details.
