### ISSUE TITLE
Parse request data to object

### ISSUE THREAD

**Issue by uncle-lv** [apiflask/apiflask#477]
I perfer getting an object instead of dict, when work with request data. Will APIFlask support it in the future?
Just like [FastAPI](https://fastapi.tiangolo.com/tutorial/body/#import-pydantics-basemodel).

There is an example.
```python
class PetIn(Schema):
    name = String(required=True, validate=Length(0, 10))
    category = String(required=True, validate=OneOf(['dog', 'cat']))


@app.post('/pets')
@app.input(PetIn)
def create_pet(json_data: PetIn):
    name = json_data.name
    category = json_data.category
    return {'message': 'created'}, 201
```

**Comment by tsokalski** [comment]
I'm not the author or a maintainer of this project, but I think the documentation suggests you can do this using `marshmallow-dataclass`: https://apiflask.com/schema/#use-dataclass-as-data-schema. Hope this helps!
