### ISSUE TITLE
LOCAL_SPEC_JSON_INDENT

### ISSUE THREAD

**Issue by odigity** [apiflask/apiflask#482]
I'm on Ubuntu 22.04 using Python 3.11, Flask 2.3.3, and APIFlask 2.1.

According to the [docs](https://apiflask.com/configuration/#local_spec_json_indent), the `LOCAL_SPEC_JSON_INDENT` setting defaults to 2, but when I look at (or download) the spec from /openapi.json, it's contained on a single line.

Furthermore, when I try to set the indent to 4:

`app.config[ "LOCAL_SPEC_JSON_INDENT" ] = 4`

It has no effect.  The spec is still contained within a single line.

Am I misunderstanding what the setting is for?

**Comment by greyli** [comment]
It's used to set the indentation for the **local spec**. When the `SYNC_LOCAL_SPEC` is `True`, APIFlask will create a local spec file in the root of your project.

See more info about indentation here: https://apiflask.com/openapi/#the-indentation-of-the-json-spec

> When you view the spec from your browser via /openapi.json, if you enabled the debug mode or set the configuration variable JSONIFY_PRETTYPRINT_REGULAR to True, the indentation will set to 2. **Otherwise, the JSON spec will be sent without indentation and spaces to save the bandwidth and speed the request.**
