### ISSUE TITLE
Deprecation warning with Flask 3.0

### ISSUE THREAD

**Issue by pamelafox** [apiflask/apiflask#488]
In attempt to update Flask, I am seeing this deprecation warning:

  /opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/apiflask/scaffold.py:82: DeprecationWarning: The '__version__' attribute is deprecated and will be removed in Flask 3.1. Use feature detection or 'importlib.metadata.version("flask")' instead.
    if flask.__version__ < '2.' or hasattr(f, '_sync_ensured'):

Seen here:

https://github.com/pamelafox/flask-charts-api-container-app/actions/runs/6377076836/job/17305088496?pr=25

Environment:

- Python version: 3.11
- Flask version: 3.0
- APIFlask version: 1.3.1

**Comment by greyli** [comment]
This reference in `scaffold.py` has been removed from APIFlask 2.0. And I just removed other references in #502.
