### ISSUE TITLE
`pagination_builder` data is not always compliant with PaginationSchema

### ISSUE THREAD

**Issue by vgrafe** [apiflask/apiflask#500]
Apologies if this is a dependency bug!

When using `pagination_builder` on a small query, for example returning 1 item for a page sized to 10 items, the resulting pagination data has a property of "next" set to an empty string. This might induce errors when for example validating the data returned by apiflask in a client app. 

It seems that returning an empty string value is correct in that scenario, and maybe `PaginationSchema` is what needs to be updated to allow empty string or optional values.

**Comment by greyli** [comment]
> This might induce errors when for example validating the data returned by apiflask in a client app.

The output data will not be validated (but will be formatted). APIFlask (marshmallow) will only validate the input data.
