### ISSUE TITLE
Support adding headers to the response schema

### ISSUE THREAD

**Issue by greyli** [apiflask/apiflask#507]
### Discussed in https://github.com/apiflask/apiflask/discussions/496

<div type='discussions-op-text'>

<sup>Originally posted by **iressstevenson** October 13, 2023</sup>
In the input we can specify location but not in the output.
Is there are way to specify output headers for the api spec?</div>

**Comment by greyli** [comment]
Assigned to @uncle-lv for [CodeKitchen Song of Open Source Sprint 1](https://codekitchen.community/t/topic/1122)

**Comment by uncle-lv** [comment]
What should the API for this feature look like? Could you provide an example?
