### ISSUE TITLE
Support `from apiflask import current_app`

### ISSUE THREAD

**Issue by uncle-lv** [apiflask/apiflask#522]
Is there any way to get `current_app` with `from apiflask import current_app` instead of `from flask import current_app`.
I think it's more consistent to get `current_app` directly from `apiflask`.

Now:
```python
from flask import current_app

current_app.config.get("BAR")
```

What I want:
```python
from apiflask import current_app

current_app.config.get("BAR")
```

**Comment by greyli** [comment]
There is no difference between these two import methods. If we re-import the `current_app` with APIFlask, what about the `session`, `request`, `g`, etc.? It will be more inconsistent.

I would like to keep unchanged objects in the `flask` module.

**Comment by uncle-lv** [comment]
Just a suggestion. It's OK keeping them in `Flask`.
