### ISSUE TITLE
Add support for a --quiet flag for the spec command

### ISSUE THREAD

**Issue by tsokalski** [apiflask/apiflask#548]
The `flask spec` command currently always prints output to stdout. In cases where the output is being directed to a file, a `--quiet` command option (or similar) would be useful to pipe the results to the output file without printing them as well.

**Comment by Muzych** [comment]
[About Flask Spec](https://apiflask.com/openapi/#the-flask-spec-command)
the document said that you could add `--output` after flask spec command.
Such as `flask spec --output openapi.json`

**Comment by tsokalski** [comment]
> [About Flask Spec](https://apiflask.com/openapi/#the-flask-spec-command) the document said that you could add `--output` after flask spec command. Such as `flask spec --output openapi.json`

Yeah, that's useful, but I'm looking to reduce output noise - my current spec is over 20k lines long, and printing the whole thing in a build pipeline while writing to a file is a bit distracting 😅.

I've opened #550 to achieve what I'm seeking.
