### ISSUE TITLE
Can APIFlask support Quart?

### ISSUE THREAD

**Issue by Cyberbolt** [apiflask/apiflask#553]
Hello, Greyli!

As time has progressed, the AsyncIO ecosystem has significantly matured, making asynchronous support a key component of any excellent web framework. Two years ago, I raised a question in the Flask [Issues](https://github.com/pallets/flask/issues/4661): Is it possible to natively support ASGI in Flask? At that time, this question was not thoroughly resolved.

Now, I am contemplating the possibility of APIFlask supporting Quart. This improvement would grant developers the freedom to choose between WSGI and ASGI, significantly enhancing APIFlask's adaptability in modern web application development, and potentially winning wider developer favor. I am very willing to participate in the development of this project in my free time (although it may not be in the near future).

I look forward to seeing Flask and APIFlask continue to progress in this direction, thank you!

**Comment by greyli** [comment]
Hi Cyberbolt, thank you for bringing this suggestion. Unfortunately, we currently have no plan to migrate to Quart. Maintaining two frameworks at the same time will be too expensive.

Welcome to contribute to APIFlask!
