### ISSUE TITLE
Create Combo Box

### ISSUE THREAD

**Issue by raulblanxart** [apiflask/apiflask#555]
Hi, I want to create a combo box like it:

![combobox](https://github.com/apiflask/apiflask/assets/163514599/3633f057-2ede-4e67-8b80-c36983b8e9d4)

I'ts posible to create now? or it's necessary to develop it?

Thanks

**Comment by greyli** [comment]
We can't create an input box as we only use Swagger UI to render the OpenAPI YAML file. You may refer to https://github.com/swagger-api/swagger-ui for more details.
