### ISSUE TITLE
unexpected keyword argument 'json_data' when using marshmallow_dataclass

### ISSUE THREAD

**Issue by laike9m** [apiflask/apiflask#569]
```python
@dataclass()
class TransactionData:
    customer_id: str

@dataclass
class TransactionInfo:
    Schema: ClassVar[Type[Schema]]  # for type checker
    data: TransactionData = field(metadata={"unknown": EXCLUDE})

@app.post("/paid")
@app.input(TransactionInfo.Schema(unknown=EXCLUDE))
def paid(transaction_info: TransactionInfo):
    return f"transaction from customer: {transaction_info.data.customer_id}"
```

Sending requests to `/paid` triggers an error
> TypeError: paid() got an unexpected keyword argument 'json_data'

It seems that APIFlask does not know it's interacting with `marshmallow_dataclass`

Environment:

- Python version: 3.12.4
- Flask version: 3.0.3
- APIFlask version: 2.1.1

**Comment by laike9m** [comment]
A mitigation is to just write `def paid(json_data: TransactionInfo):`, though would still be nice if this gets fixed.

**Comment by uncle-lv** [comment]
You can set a custom argument name with `arg_name`.
```python
@app.post("/paid")
@app.input(TransactionInfo.Schema(unknown=EXCLUDE), arg_name='transaction_info')
def paid(transaction_info: TransactionInfo):
    return f"transaction from customer: {transaction_info.data.customer_id}"
```

It's an important change in [APIFlask 2.0.0](https://apiflask.com/changelog/#version-200).
![图片](https://github.com/apiflask/apiflask/assets/88037946/2d5b9099-5d06-4a61-8379-297789aa60d9)

Read the [doc](https://apiflask.com/usage/#use-appinput-to-validate-and-deserialize-request-data) for more details.

**Comment by uncle-lv** [comment]
I'll update [Data Schema](https://apiflask.com/schema/#use-dataclass-as-data-schema) chapter in the doc later.

**Comment by laike9m** [comment]
Awesome, thanks!
