### ISSUE TITLE
Using FileSchema in output decorator causes AttributeError: 'FileSchema' object has no attribute 'many'

### ISSUE THREAD

**Issue by hinte-it** [apiflask/apiflask#576]
I'm not entirely sure if I'm supposed/allowed to just return a string when using `FileSchema`, sorry if that is the source of the error.

Minimal code example:
```python
from apiflask import APIFlask, abort
from apiflask.schemas import FileSchema

app = APIFlask(__name__)

@app.get('/getfile')
@app.output(FileSchema, content_type='text/plain')
def get_file():
    return "text"
```

Traceback:
```
[2024-07-02 15:51:02,797] ERROR in app: Exception on /getfile [GET]
Traceback (most recent call last):
  File "/home/xyz/.local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/xyz/.local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/xyz/.local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/xyz/.local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/xyz/.local/lib/python3.10/site-packages/apiflask/scaffold.py", line 517, in _response
    return _jsonify(rv), status_code
  File "/home/xyz/.local/lib/python3.10/site-packages/apiflask/scaffold.py", line 484, in _jsonify
    many = schema.many  # type: ignore
AttributeError: 'FileSchema' object has no attribute 'many'
```

Environment:

- Python version: 3.10.12
- Flask version: 3.0.3
- APIFlask version: 2.1.1

**Comment by uncle-lv** [comment]
`FileSchema` should work with `send_from_directory`.
Read the [doc](https://apiflask.com/api/schemas/#apiflask.schemas.FileSchema) for more details.

**Comment by uncle-lv** [comment]
If you want to return the content of a file, please read the content first, then return it directly.
```python
@app.get('/getfile')
def get_file():
    with open(filename) as f:
        text = f.read()
    return text
```

**Comment by uncle-lv** [comment]
> I forgot to add that this looks a bit similiar to #11
> 
> I tried modifying `FileSchema.__init__()` to add a call to `super().__init__()` like this:
> 
> ```python
> def __init__(...) -> None:
>     super().__init__()
>     self.type = type
>     self.format = format
> ```
> 
> This fixes the `AttributeError` (and a bunch of similiar errors that happened when I tried to manually add missing attributes to `FileSchema`), but results in a wrong response of `{}` with `Content-Type: application/json`.
> Test code & response

The response is empty, because `FileSchemaTest` just like [`EmptySchema`](https://github.com/apiflask/apiflask/blob/8df4e16e7dd7ce4402a78223f71044513681fc67/src/apiflask/schemas.py#L62), they don't include any field.

**Comment by hinte-it** [comment]
Ah, thanks! Should've looked into that, sorry.

I updated my code to use `send_from_directory` (and the regular FileSchema instead of the FileSchemaTest from above), but that results in the same `AttributeError`.

<details><summary>Test code & Traceback</summary>
<p>

app.py

```python
from apiflask import APIFlask, abort
from apiflask.schemas import Schema, FileSchema
from flask import send_from_directory

app = APIFlask(__name__)

@app.get('/getfile')
@app.output(FileSchema, content_type='text/plain')
def get_file():
    send_from_directory("/tmp", "testfile")
``` 

Exception with traceback:

```
[2024-07-03 09:49:41,103] ERROR in app: Exception on /getfile [GET]
Traceback (most recent call last):
  File "/home/xyz/.local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/xyz/.local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/xyz/.local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/xyz/.local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/xyz/.local/lib/python3.10/site-packages/apiflask/scaffold.py", line 517, in _response
    return _jsonify(rv), status_code
  File "/home/xyz/.local/lib/python3.10/site-packages/apiflask/scaffold.py", line 484, in _jsonify
    many = schema.many  # type: ignore
AttributeError: 'FileSchema' object has no attribute 'many'
127.0.0.1 - - [03/Jul/2024 09:49:41] "GET /getfile HTTP/1.1" 500 -
``` 
</p>
</details> 

FWIW: Using FileSchemaTest with this results in the empty dict being sent [as above](https://github.com/apiflask/apiflask/issues/576#issuecomment-2203389596), and `FileSchema(type='string', format='binary')` vs `FileSchema` makes no difference.

**Comment by hinte-it** [comment]
> If you want to return the content of a file, please read the content first, then return it directly.
> 
> ```python
> @app.get('/getfile')
> def get_file():
>     with open(filename) as f:
>         content = f.read()
>     return content
> ```

This works, but results in `Content-Type: text/html`, while the OpenAPI docs state `application/json`.

Returning a `flask.Response(content, mimetype='text/plain')` results in the correct Content-Type being sent, but of course doesn't change anything about the OpenAPI docs.

Finally, this does exactly what I want and doesn't error out:
```python
@app.get('/getfile')
@app.output(FileSchema, content_type="text/plain")
def get_file():
    return Response("hello\n", mimetype='text/plain')
```
(Reading a file and passing its contents to Response instead of a hard-coded string also works, of course.)

I personally would consider this to be a work-around, but I'll leave making the call about this up to you.
Also, (as long as I didn't miss anything) the code in my previous comment is pretty much the same as the example code in the docs, so if you decide not to change whatever causes the `AttributeError`, the docs should probably be changed.

**Comment by uncle-lv** [comment]
> Ah, thanks! Should've looked into that, sorry.
> 
> I updated my code to use `send_from_directory` (and the regular FileSchema instead of the FileSchemaTest from above), but that results in the same `AttributeError`.
> Test code & Traceback
> 
> app.py
> 
> ```python
> from apiflask import APIFlask, abort
> from apiflask.schemas import Schema, FileSchema
> from flask import send_from_directory
> 
> app = APIFlask(__name__)
> 
> @app.get('/getfile')
> @app.output(FileSchema, content_type='text/plain')
> def get_file():
>     send_from_directory("/tmp", "testfile")
> ```
> 
> Exception with traceback:
> 
> ```
> [2024-07-03 09:49:41,103] ERROR in app: Exception on /getfile [GET]
> Traceback (most recent call last):
>   File "/home/xyz/.local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/xyz/.local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/xyz/.local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/xyz/.local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
>   File "/home/xyz/.local/lib/python3.10/site-packages/apiflask/scaffold.py", line 517, in _response
>     return _jsonify(rv), status_code
>   File "/home/xyz/.local/lib/python3.10/site-packages/apiflask/scaffold.py", line 484, in _jsonify
>     many = schema.many  # type: ignore
> AttributeError: 'FileSchema' object has no attribute 'many'
> 127.0.0.1 - - [03/Jul/2024 09:49:41] "GET /getfile HTTP/1.1" 500 -
> ```
> 
> FWIW: Using FileSchemaTest with this results in the empty dict being sent [as above](https://github.com/apiflask/apiflask/issues/576#issuecomment-2203389596), and `FileSchema(type='string', format='binary')` vs `FileSchema` makes no difference.

Just remove `@app.output(FileSchema, content_type='text/plain')`and add `return send_from_directory("/tmp", "testfile")`.

**Comment by uncle-lv** [comment]
> > If you want to return the content of a file, please read the content first, then return it directly.
> > ```python
> > @app.get('/getfile')
> > def get_file():
> >     with open(filename) as f:
> >         content = f.read()
> >     return content
> > ```
> 
> This works, but results in `Content-Type: text/html`, while the OpenAPI docs state `application/json`.
> 
> Returning a `flask.Response(content, mimetype='text/plain')` results in the correct Content-Type being sent, but of course doesn't change anything about the OpenAPI docs.
> 
> Finally, this does exactly what I want and doesn't error out:
> 
> ```python
> @app.get('/getfile')
> @app.output(FileSchema, content_type="text/plain")
> def get_file():
>     return Response("hello\n", mimetype='text/plain')
> ```
> 
> (Reading a file and passing its contents to Response instead of a hard-coded string also works, of course.)
> 
> I personally would consider this to be a work-around, but I'll leave making the call about this up to you. Also, (as long as I didn't miss anything) the code in my previous comment is pretty much the same as the example code in the docs, so if you decide not to change whatever causes the `AttributeError`, the docs should probably be changed.

Actually `FileSchema` just generate the OpenAPI docs and don't participate in serialization. This is why `AttributeError` occurs.

**Comment by uncle-lv** [comment]
> Also, (as long as I didn't miss anything) the code in my previous comment is pretty much the same as the example code in the docs, so if you decide not to change whatever causes the `AttributeError`, the docs should probably be changed.

This is a good suggestion. The name of `FileSchema` can mislead developers into thinking that it will work like other Schemas, but in fact it don't.

Maybe we should discuss it with its author @greyli .

**Comment by greyli** [comment]
> > Ah, thanks! Should've looked into that, sorry.
> > I updated my code to use `send_from_directory` (and the regular FileSchema instead of the FileSchemaTest from above), but that results in the same `AttributeError`.
> > Test code & Traceback
> > app.py
> > ```python
> > from apiflask import APIFlask, abort
> > from apiflask.schemas import Schema, FileSchema
> > from flask import send_from_directory
> > 
> > app = APIFlask(__name__)
> > 
> > @app.get('/getfile')
> > @app.output(FileSchema, content_type='text/plain')
> > def get_file():
> >     send_from_directory("/tmp", "testfile")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Exception with traceback:
> > ```
> > [2024-07-03 09:49:41,103] ERROR in app: Exception on /getfile [GET]
> > Traceback (most recent call last):
> >   File "/home/xyz/.local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
> >     response = self.full_dispatch_request()
> >   File "/home/xyz/.local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
> >     rv = self.handle_user_exception(e)
> >   File "/home/xyz/.local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
> >     rv = self.dispatch_request()
> >   File "/home/xyz/.local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
> >     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
> >   File "/home/xyz/.local/lib/python3.10/site-packages/apiflask/scaffold.py", line 517, in _response
> >     return _jsonify(rv), status_code
> >   File "/home/xyz/.local/lib/python3.10/site-packages/apiflask/scaffold.py", line 484, in _jsonify
> >     many = schema.many  # type: ignore
> > AttributeError: 'FileSchema' object has no attribute 'many'
> > 127.0.0.1 - - [03/Jul/2024 09:49:41] "GET /getfile HTTP/1.1" 500 -
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > FWIW: Using FileSchemaTest with this results in the empty dict being sent [as above](https://github.com/apiflask/apiflask/issues/576#issuecomment-2203389596), and `FileSchema(type='string', format='binary')` vs `FileSchema` makes no difference.
> 
> Just remove `@app.output(FileSchema, content_type='text/plain')`and add `return send_from_directory("/tmp", "testfile")`.

There is no need to remove the `@app.output(FileSchema, content_type='text/plain')`. In the provided example, you forget to add `return` statement. 

```diff
from apiflask import APIFlask, abort
from apiflask.schemas import Schema, FileSchema
from flask import send_from_directory

app = APIFlask(__name__)

@app.get('/getfile')
@app.output(FileSchema, content_type='text/plain')
def get_file():
-    send_from_directory("/tmp", "testfile")  # <--- 
+   return send_from_directory("/tmp", "testfile") 
```

For the `AttributeError`, the serialization call to the file schema raises this error. I'll improve the handling of `FileSchema` and skip serialization for it in #578.

**Comment by uncle-lv** [comment]
> There is no need to remove the `@app.output(FileSchema, content_type='text/plain')`. In the provided example, you forget to 

Right. It's OK to reserve `@app.output(FileSchema, content_type='text/plain')` here, which can generate the OpenAPI docs for you.
I just made a mistake.

**Comment by hinte-it** [comment]
Awesome, thanks a ton for the quick responses, the info and the fix!

(Also, sorry for the mistakes on my side!)
