### ISSUE TITLE
Invalid spec and missing requestBody when using json_or_form

### ISSUE THREAD

**Issue by elbakerino** [apiflask/apiflask#600]
When using `json_or_form` in `location`, the produced request spec is invalid and misses the `requestBody`.

e.g.:
`@app.input(SomeRequest, location='json_or_form')`

Produces this invalid spec:

```json
{
    "/some-request": {
        "post": {
            "parameters": [
                {
                    "in": "json_or_form",
                    "name": "input",
                    "required": false,
                    "schema": {
                        "type": "string"
                    }
                }
            ],
            "responses": {
                "... redacted": ""
            },
            "summary": "Some Request"
        }
    }
}
```

Instead of `requestBody` it has `parameters`, with an invalid `in` [parameter-locations](https://swagger.io/specification/#parameter-locations).

Example of requestBody with multiple types:

```json
{
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "$ref": "#/components/schemas/Order"
                }
            },
            "application/xml": {
                "schema": {
                    "$ref": "#/components/schemas/Order"
                }
            },
            "application/x-www-form-urlencoded": {
                "schema": {
                    "$ref": "#/components/schemas/Order"
                }
            }
        }
    }
}
```

See [petstore3.swagger.io/api/v3/openapi.json](https://petstore3.swagger.io/api/v3/openapi.json) for a full example.

> While the OpenAPI file is unusable, the request parsing works in clients with a manual defined `content-type` header.

Environment:

- Python version: 3.10
- Flask version: 3.0.3
- APIFlask version: 2.2.0

**Comment by greyli** [comment]
I just found a way to fix this. But I'm unsure which content type should be used for `json_or_forms` when generating the OpenAPI spec, `application/json` (JSON) or `application/x-www-form-urlencoded` (form)?

**Comment by elbakerino** [comment]
All supported types, similar to the `updatePet` example:

```json
   "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "$ref": "#/components/schemas/Pet"
                }
            },
            "application/x-www-form-urlencoded": {
                "schema": {
                    "$ref": "#/components/schemas/Pet"
                }
            }
        }
    },
```

Or even three? I would be more for a files validation and disallowing uploads.

Even when `files` are not provided, based on checks it still provides the form data when send with `multipart/form-data` and configured as `json_or_form`.

```json
   "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "$ref": "#/components/schemas/Pet"
                }
            },
            "application/x-www-form-urlencoded": {
                "schema": {
                    "$ref": "#/components/schemas/Pet"
                }
            },
            "multipart/form-data": {
                "schema": {
                    "$ref": "#/components/schemas/Pet"
                }
            }
        }
    },
```

- `json_or_form` content-type headers and what is provided in `json_or_form_data`
  - `application/json`: json data
  - `application/x-www-form-urlencoded`: form data
  - `multipart/form-data`: form data, but no files

**Comment by greyli** [comment]
I will fix this and make a new release tomorrow. Sorry for the late response.

**Comment by greyli** [comment]
[2.2.1](https://github.com/apiflask/apiflask/releases/tag/2.2.1) released, thanks!

**Comment by elbakerino** [comment]
Thanks! No worries, I mostly need way longer, works as expected now!
